name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  nonreg-sim:
    # Call the workflow from CI repo
    uses: deuskane/asylum-ci/.github/workflows/vhdl-ci.yml@main
    with:
      nonreg_type: sim